# Generated by Django 5.1.1 on 2024-09-22 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/images/'),
        ),
    ]
