# Generated by Django 5.1.1 on 2024-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating_created_at_alter_movieentry_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movieentry',
            name='movie_entry_title_5a4f63_idx',
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='movieentry',
            index=models.Index(fields=['title', 'author', 'release_date', 'genre', 'movie_id'], name='movie_entry_title_322a1d_idx'),
        ),
    ]
